module.exports = [
	"Baby's at the punch bowl",
	"with a glass for you to fill",
	"if you empty it with her",
	"in the time she has to kill",
	"Kill kill kill me",
	"Baby's in the punch bowl",
	"wants you to help yourself",
	"and she'll remember nothing",
	"so there'll be nothing to tell",
	"Tell tell tell tell me",
	"I'm not saying, I'm not saying, I'm just saying",
	"Baby's on the punch bowl",
	"gonna ride it off to bed",
	"Yours or any bed'll do really",
	"as long as it ain't the one she left",
	"Left left left left me",
	"Tell me you want me to think ",
	"You can lead me to water you can make me drink",
	"I trust you if you say it's good",
	"You wouldn't hurt me and I don't think you could",
	"Tell me what I don't need to keep",
	"I over-packed and the sidewalk is steep",
	"To your cathedral at the top of Nob Hill",
	"It makes me tired and dear it always will",
	"Tell me why I haven't been healed",
	"I haven't changed and nothings been revealed",
	"And what's in the blood of the way and the light",
	"That takes my sin Sunday morning and",
	"Makes me drunk at night",
	"Tell me that I'm more than a dream",
	"A golden hell prize you failed to redeem",
	"Don't tell me that you've always known",
	"That I'd wake up first, and you'd wake up alone",
	"The sweet young man",
	"Goes walking down the street",
	"wiping blood off his hands",
	"And it doesn't look good but he does what he can",
	"To erase the signs",
	"Of the nightmare he faced at the scene of the crime",
	"She snuck up behind him",
	"As he knelt by her victim",
	"She whispered I knew you'd come",
	"But there's nothing to be done",
	"And if I were you I'd run",
	"Cause no one cares",
	"About how you felt",
	"When they see any sign of guilt",
	"You kissed its face",
	"You held its hand",
	"You always were a sweet young man",
	"He's still a mess",
	"So he hires a car",
	"To take him to the fountain at Balboa park",
	"Where he used to play",
	"When he was young",
	"I'm back in the moment where I belong",
	"Turns out four years was four years too long",
	"Its over and I'm over it",
	"She sang me a song that I wrote for her",
	"Then she said I like the tune but not the words",
	"Its over and I'm over it",
	"You collected the moments I threw away",
	"Said to yourselves he's gonna want them back",
	"The day it's over",
	"And he's over it",
	"Friends let's drink 'til our hearts break open",
	"And our hands feel empty",
	"Though they're full all the time",
	"It's so nice in here I'm so glad you're here",
	"Can we just stay here all the time",
	"Walk me home we'll watch the sun come up",
	"Don't leave me alone 'cause I've been left enough",
	"It's over I'll get over it",
	"Friends let's drink to my indiscretions",
	"I woke up with a number and a name",
	"That I don't want that I won't use again",
	"But would you proofread any messages I send",
	"O woman I'm your servant",
	"I don't know anything but I'm ready to learn",
	"O woman I'm starving for your approval",
	"Be kind to me",
	"The big city calls and your daughters are smiling",
	"In the windows of apartment buildings",
	"I bet I look about as small as I feel",
	"Thank you jesus can I have another",
	"And another",
	"Thank you lord",
	"But if it pleases thee to have them",
	"Banging down the door",
	"Couldst thou let 'em know what they're in for",
	"Ain't good for you or me or them",
	"Amen",
	"O woman I'm your servant",
	"Asking for the right to look you in the eye",
	"O woman I'm dying for you to notice",
	"How far I've come",
	"I'm moving downtown and your",
	"Daughters are walking by me",
	"I believe they're still deciding",
	"If they like having me around",
	"If they like having me around",
	"I need to know why",
	"Goodwill's coming by to collect a box",
	"I filled with things I hate about myself",
	"Things I liked before I got here",
	"Then it'll pick her up and we'll do",
	"Anything she wants or anything they want",
	"Or anything you want o woman I don't care",
	"Lord I'd be in your debt",
	"If you'd help me forget",
	"That heaven's mine for trying",
	"Cause lord I don't know why",
	"You'd give me so much life",
	"I'm coming back my friends",
	"From the deep and bitter end",
	"Where I was so concerned",
	"That we would be the ones who burned",
	"The more scared the safer",
	"The more grateful for the grape juice",
	"And the wafer",
	"I sound done",
	"And I feel done",
	"But I'm not done",
	"Unless he'd give up on a lost son",
	"I need to hear him say",
	"You and your friends can come in",
	"Your thoughts and that girl can come in",
	"Your parents and brothers are here",
	"I let them in",
	"Who told you I wouldn't let you all in",
	"You are my children",
	"Heaven shine through the stars",
	"The city lights and the nearest bar",
	"Where I'll be with my friends",
	"Hiding from the bitter end",
	"The armor and the weapons",
	"Were a strange way to show them my affection",
	"I sound done",
	"And I feel done",
	"But I'm not done",
	"Nothing nothing then a kiss",
	"In the middle of the street",
	"And I'm loosening my grip",
	"On the throat of a bad dream",
	"Turning gold above your head",
	"A bell to ring me to my knees",
	"Do you darling 'til you're dead",
	"Or do you darling 'til you're bored",
	"With this ringing I thee wed",
	"Nothing then a haloed whore",
	"And an angel that she bribed",
	"And a god he's working for",
	"Come to take me from your side",
	"Where I wake in a cold sweat",
	"Wringing love out of my life",
	"So do you darling 'til you're dead",
	"Or do you darling 'til you're bored",
	"It'll happen",
	"It's gonna happen babe",
	"But it hasn't happened yet",
	"I'm not gonna let you get",
	"ahead of yourself",
	"It's your Achilles heel",
	"Though I want it as bad as you",
	"We've gotta try to see it through",
	"Our own excitement",
	"Your excitement babe",
	"Hasn't let that happen yet",
	"and it won't if you forget",
	"what happened last time",
	"You call me, why do you call me",
	"And why do I answer, when I know",
	"Oh I know you were crying",
	"Why are you crying",
	"And how can you say that, when you know",
	"Oh you know, that you were the sun giving up behind the golden gate",
	"Now you’re the bum begging up and down the lower hate",
	"Oh you know, that you were the band going out to play one more song",
	"Now you’re the giant out on second ‘cause you thought he was gone",
	"I call her, why do I call her",
	"And why does she answer, when she knows",
	"oh she knows I was laughing",
	"Why am I laughing",
	"Oh and how can I say that when I know, oh I know",
	"that I was a fire-escape party over union square",
	"Now I’m a cab driver fucking over every fare",
	"Oh I know, that I was a young Dylan tossing off the perfect verse",
	"Now I’m another damn Yankee can’t toss to first (woohoohoo)",
	"Lord I can’t toss it to first (woohoohoo)",
	"Oh I can’t toss it to first",
	"Oh we know that we were the band going out to play one more song",
	"Now you’re the giant out on second 'cause you thought he was gone…",
	"About a year from now",
	"I wake up in",
	"The arms of who i want",
	"Without the need to hide our nakedness",
	"In pure and holy thought",
	"And by the blessing thrice",
	"The shutters never closed",
	"The bed still made",
	"The early afternoon as morning mmm's",
	"Hey are you awake?",
	"You take my love and my lust",
	"Cold clock my mind ahhh",
	"Turn in my keys to the kingdom",
	"Let not my body die",
	"You are, you are, you are to me",
	"Like a very very wild thing",
	"These are to me the games i play",
	"Before i herad they were insane",
	"To play you are to me",
	"Like a very very wild thing",
	"About a year from now",
	"I say goodnight and kiss kiss kiss the phone",
	"To sleep the sleep of one",
	"Who finally wouldnt rather sleep alone",
	"You take my love and my lust",
	"Cold clock my mind ahhhh",
	"Turn in my keys to the kingdom",
	"Let not my body die",
	"You are, you are, you are to me",
	"Like a very very wild thing",
	"These are these are to me the games i play",
	"Before i heard they were insane",
	"To ply you are to me ",
	"Like a very very wild thing",
	"You take my love and my lust",
	"Cold clock my mind ahhhh",
	"Turn in my keys to the kingdom",
	"Let not my body die",
	"You turn my blood as it boils",
	"Plays it clean",
	"I wash my fear away",
	"God if i dont stop now",
	"I know this wont be half of what its gonna take",
	"You are, you are, you are to me",
	"Like a very very wild thing",
	"Don't need no chorus, cash or candy now",
	"Don't need no callous crush to come around",
	"And I don't know who you are",
	"But you and your boys ain't got nothing on me",
	"I've had my last eight drinks in here for free",
	"'cause that's my friend tending bar",
	"Yeah, i got a friend who tends bar",
	"(and she won't let me tip her)",
	"When I get tired tonight she'll take me home, ",
	"and if it's cold under the covers",
	"she'll keep me warm",
	"Sweet, Lovely Friend Who Tends Bar",
	"(and lovely friends who tend bar",
	"can always feel lovelier)",
	"Alex, Short and Sweet",
	"leave your boyfriends at home and the drinks are on me next week",
	"He seems like a real good guy",
	"but you're only as good as your last goodbye",
	"Alex, let your long hair down",
	"like the prettiest brush you could ever use to paint this town",
	"because you know as well as I do",
	"that we're only as good as our last goodbyes",
	"What will we do, where will we go?",
	"Alexandra, I don't really know",
	"When will it end?",
	"Whenever you want it to",
	"Alex to your health!",
	"May you never outgrow the need to outdo yourself",
	"and heed the jealous cry",
	"of a sitting duck stuck to his last goodbye",
	"Skyward they flew 'til it was as far",
	"to the street as it was to the stars",
	"and to stardust as peanut shells on the parlor floor",
	"What have we done, where have we gone?",
	"Nothing, above and beyond",
	"When will it end?",
	"Alexandra, it's already done",
	"I told you honey, short and sweet!",
	"It's a damn sight better than long and bitter, don't you think?",
	"Keep your feet wet and your eyes dry",
	"'cause you're only as good as your last goodbye",
	"you're only as good as your last goodbye",
	"yeah, you're only as good as your last goodbye",
	"Rye Whiskey makes the band sound better",
	"Makes your baby cuter, makes itself taste sweeter. Oh, boy!",
	"Rye whiskey makes your heart beat louder",
	"Makes your voice seem softer, makes the back room hotter, oh, but",
	"Rye thoughts aren't good thoughts, Boys",
	"Have I ever told you about the time I",
	"Rye whiskey wraps your troubles up into a bright blue package",
	"Ties a bow around it. Oh, boy!",
	"Just throw it on the pile in the corner",
	"See, you're not alone in not being alone tonight, but",
	"Rye love isn't good love, Boys",
	"Have I ever told you about the time I",
	"I used to wake up bright and early",
	"Got my work done quickly, held my baby tightly. Oh, boy!",
	"Rye whiskey makes the sun set faster",
	"Makes the spirit more willing but the body weaker because",
	"Rye sleep isn't good sleep, Boys",
	"Have I ever told you about the time I",
	"Took it and took her for granted?",
	"How I took it and took her for granted?",
	"So let's take some and take them all for granted",
	"Oh, boy!",
	"We go to bed and you fall asleep, fall asleep, not me",
	"we go to bed and I lie awake, lie awake and",
	"float out the window and down the street, over the bridge and",
	"into the village for a little break from me, meaning us",
	"I float away and you disappear, disappear",
	"some pretty young villager takes my hand and leads me to more",
	"pretty young villagers forming a ring, forming a ring around",
	"a bonfire built on a line in the sand between me an us",
	"Am I lost, have I lost, have they thrown me on the fire",
	"there to dance in the flames, far enough from you to wonder",
	"if me still means us",
	"She leads me to the end of the night. A boyfriend of hers is there",
	"You're on his arm, but our eyes don't meet, our eyes don't meet 'cause",
	"we only have eyes for fueling the fire, being melted down and reformed",
	"in the image of wilder things, wilder things than us",
	"Are we lost, have we lost, have they thrown us on the fire",
	"there to dance in the flames, far enough from one another",
	"We fed them to the flames, but they're just getting colder and colder",
	"The boy's at least half again as selfish, and the girl's feeling a day",
	"older per hour",
	"but there's no help for them now",
	"because together looks good when you're alone looks good",
	"when you're together",
	"and it takes a village older and less inclined to say which is better to say",
	"which would be better",
	"I told her once",
	"Get thee behind me",
	"Cover up Missy for the love of God",
	"I can't not look, I can't not look",
	"And I can’t do a thing about what I saw",
	"Though I wish I could, I wish I could",
	"She told me once",
	"Sit down beside me",
	"I told her twice",
	"To get thee behind me",
	"Strip down Missy it's 11 AM",
	"I'm gonna wake up soon, gonna wake up soon",
	"I bet you say that to all of the dreaming men",
	"That get lucky with you, get lucky with you",
	"She told me once",
	"Lay down beside me",
	"And I laid down beside her",
	"Too real, too quick, too close to home",
	"Too much to take the task alone",
	"Can I have just a little taste",
	"Too hot, too sweet, too bad and too late",
	"I told her three times",
	"Get thee behind me",
	"Float away Missy like a wisp of smoke",
	"That I could’ve inhaled, maybe could’ve inhaled",
	"And I'll sing your praises everywhere I go",
	"Such a pretty girl, such a beautiful girl",
	"She told me once",
	"You won't forget me",
	"And I won't forget her",
	"Captain, if it's all the same to you",
	"let me ready a lifeboat--",
	"Sorry, son, though your heart may be true",
	"you'd best get it stoutened or I'll run it through",
	"Here's a sip to wash the wicked words back down your throat",
	"I know my ship, my catch, and my men",
	"and I know what you think you've seen--",
	"Captain, you may well take offense",
	"but something has to be done nonetheless",
	"or it's off to Davy's Locker for to calm the sea",
	"Sir, it's angry, you're not listening, I saw a woman, I heard a bell",
	"Captain, the rum welling up in your eyes",
	"will chase neither care nor curse--",
	"Nor will abstinence, son, for my fertile mind bore this ghost",
	"of the true sove that I've left behind, and you'll make her haunt",
	"no lifeboat while I'm gone from her",
	"I hear the peal of our wedding bells",
	"many miles away and months from now--",
	"Captain, if you can't but do well by a phantom future, you're destined",
	"to dwell and weep and gnash your teeth with all the rightly drowned",
	"Sir, I'm fighting for a home on the Fiddler's Green",
	"not for a woman and a bell",
	"Captain, the sea took your ship, catch, and men",
	"left you, me, and this lifeboat--",
	"Sorry, son, you're dead wrong again. I'll sail on with only the love you",
	"condemn, having offered up your weak heart for a safe trip home",
	"She puts my body away",
	"Next to the trash",
	"Under the sink",
	"Along with all the cleaning supplies and the things that we buy and decide we don't need",
	"Well it's damp and it's dark and it's lonely in here",
	"Next to the trash",
	"Under the sink",
	"But everyone needs some time off now and then",
	"'Cause I'm happy my friends",
	"Don't feel sorry for me",
	"She says if you're playin' the game",
	"I hope you know you won't win it",
	"And if you tell me you're next to the trash",
	"Well I'll tell you I'm in it",
	"Why would you want me to touch you if you know I don't mean it?",
	"She's right I'm mean when I'm bored",
	"So I dig through the trash looking for her",
	"She can wash herself off",
	"In the mist from the pipes",
	"We could use more of that around here that's for sure",
	"But it seems that whoever has thrown her away",
	"Has forgotten the trash under the sink",
	"Or was it a joke meant to buy her some time",
	"All the citrus and pine make it harder to think",
	"So I say if you're playing the game",
	"I hope you know you won't win it",
	"And I'll be sorry if they threw you away",
	"It's just that they didn't",
	"She says \"Boy, you'd better take it back right now and I mean it\"",
	"She puts my body away",
	"Then chases my mind up to the roof",
	"It jumps in the gutter",
	"But she pulls it out",
	"And it's all part of having a man in the house",
	"It jumps in the gutter she pulls it out",
	"And it's all part of having a man in the house",
	"Welcome home",
	"- if home it is and well you come -",
	"we've seen the smoke and smelled the fumes",
	"You went for broke",
	"then under over a couple bucks",
	"threw down the yoke and put up your dukes",
	"May a blow land",
	"where you'll feel it",
	"May your fire spread",
	"through the coal-sewn fields",
	"Fare thee well",
	"in a welfare line or thy father's will",
	"Don't kill us and we'll go your bail",
	"You hit and held",
	"and folded",
	"enthralled isn't thrilled",
	"you said, \"grow up,\" and away you sailed",
	"May the blow land",
	"where he'll see it",
	"May your fear spread",
	"through the tear-stained shores",
	"Saying, \"I never knew you.\"",
	"Welcome home",
	"- if home it is and well you come -",
	"'cause fear and fire can't consume",
	"condemn, condone",
	"or dismiss what we haven't done",
	"and he's out of salt",
	"Go dress our wounds",
	"Lay a flare down",
	"by your dull pain",
	"May he show up",
	"or may you move on",
	"He will show up",
	"or you will move on",
	"This is the song where I listen",
	"This is the song where I sit still",
	"I called the dogs off all the things I'm missing",
	"And to everyone but to you before I set sail",
	"I said good luck, good luck, good luck",
	"These are tough times",
	"But we'll get by",
	"Good luck",
	"This is the song where you speak up",
	"This is the song where you get moving",
	"You cried some trouble out into a tea cup",
	"And to me but no one else before you threw it",
	"You said good luck, good luck, good luck",
	"These are tough times",
	"But we'll get by",
	"Good luck",
	"I put a shore in front of our apartment",
	"And watched you comb the stoop for shards of porcelain",
	"Satisfied that there were none you broke the silence",
	"And after this I promise not to interrupt again",
	"This is the song where I listen",
	"This is the song where I sit still",
	"Until our heartbeats drown out the clock ticking",
	"And the song is just I love you and always will",
	"Good luck, good luck, good luck",
	"These are tough times",
	"But we'll get by",
	"Good luck",
	"These are tough times",
	"But we'll get by",
	"Good luck",
	"These are tough time",
	"But we'll get by",
	"Good luck",
	"After years of waiting nothing came",
	"As your life flashed before your eyes",
	"You realize",
	"I'm a reasonable man",
	"Get off, get off, get off my case",
	"I'm a reasonable man",
	"Get off my case",
	"Get off my case",
	"After years of waiting",
	"After years of waiting nothing came",
	"And you realize you're looking",
	"Looking in the wrong place",
	"I'm a reasonable man",
	"Get off my case",
	"Get off my case",
	"I'm a reasonable man",
	"Get off my case",
	"Get off my case",
	"Get off my case",
	"I'm a reasonable man",
	"Get off my case",
	"Get off my case",
	"Get off my case",
	"After years of waiting",
	"I'm a reasonable man",
	"Get off my case",
	"Get off my case",
	"Get off my case",
	"I'm a reasonable man",
	"Get off my case",
	"Get off my case",
	"Get off my case",
	"I'm a reasonable man",
	"Get off my case",
	"Get off my case",
	"Get off my case",
	"I'm a reasonable man",
	"Get off my case",
	"Get off my case",
	"Get off my case",
	"Did he ever live",
	"In those three and twenty years",
	"For a thing but movement and location?",
	"If she'd raised her voice",
	"Not her sparkling shallow eyes",
	"To indict my movement and location",
	"Would the battle be lost?",
	"You can watch the tape",
	"You can try to hit your spots",
	"But don't do it for anything but the thrill of movement and location",
	"Or the battle is lost",
	"Father Father Father",
	"It's been a long time how are you doing?",
	"How is your son how are his children?",
	"I bet they're just like me",
	"You must be tired tired tired",
	"Of hearing prayers like mine no need to answer",
	"Nobody likes knowing that favors",
	"Are all they'll ever be",
	"But there's this girl this girl this girl this girl this girl",
	"And I'd be the happiest backslider in the world",
	"If you would tell her it's your will for us to be together",
	"Father Father Father",
	"You've seen me try and try to make her love me",
	"I'd sell my soul to hear the one thing",
	"She thinks she'll never say",
	"But now it's Sunday Sunday Sunday",
	"And her pretty voice is rising up to ask you",
	"Like I once did like I'm about to",
	"If you could show her the way",
	"'Cause there's this girl this girl this girl this girl this girl",
	"And I'd be the happiest backslider in the world",
	"If you would tell her it's your will for us to be together",
	"I would never bother you again",
	"Father you of all gods ought to know how little to expect from people",
	"But I think you might be pleasantly surprised to see what this girl",
	"Would bring out of me",
	"There's this girl this girl this girl this girl this girl",
	"And I'd be the happiest backslider in the world",
	"If you would tell her it's your will for us to be together",
	"I would never bother you again unless you want me to",
	"Hell we'll just both hang out with you in heaven when we die",
	"Well it's no concern of yours my friend it's no concern of yours",
	"The nail that's sticking up will just get hammered to the board",
	"And it's no concern of yours my friend it's no concern of yours",
	"It's hard to hold your head up when it's in your hands",
	"To wash off last night's trouble in a clean white shirt",
	"If anyone can do it I can",
	"And it's no concern of yours my friend it's no concern of yours",
	"The finest looking apple can be rotten to the core",
	"And it's no concern of yours my friend it's no concern of yours",
	"We're not here to talk about me",
	"We're here to get things done",
	"'Cause if we do my daddy won't have ruined both his sons",
	"He's going down",
	"It's no concern of yours my friend it's no concern of yours",
	"A word can break as easy as it's spoken snarled or sworn",
	"And it's no concern of yours my friend it's no concern of yours",
	"When your name is on this building take me out for lunch",
	"After three or four Old Fashioneds tell me what you've heard",
	"Then you'd better listen closely I'll only say it once",
	"I wasn't tired",
	"I'm never tired",
	"Youth will not be wasted on this one",
	"In a dark room",
	"Another dark room",
	"She said hey you're gonna like this",
	"It's easy to like by candlelight if not under the sun",
	"Who's feeling young now?",
	"Dark room to doorway",
	"Doorway to sidewalk",
	"Youth will not be wasted on this one",
	"In a thick fog",
	"Another thick fog",
	"I said hey this isn't like me",
	"It's a little like there could be something new under the sun",
	"Who's feeling young now?",
	"They try to tell us and at times we try to listen",
	"But we can't hear a thing when all we think about are all the things we think we might be missing",
	"'Cause if we think we are we are",
	"And if we don't we aren't worth the time it takes to think of making love with who we're kissing",
	"They tried to tell us and at times we tried to listen",
	"No!",
	"She wasn't perfect",
	"Nobody's perfect",
	"Gray hair ain't a crown of wisdom",
	"When you're a young man",
	"'Til you're an old man",
	"She says hey you look a lot like",
	"Someone I liked who flew just far enough under the sun to never come down",
	"Who's feeling young",
	"They try to tell us and at times we try to listen",
	"But we can't hear a thing when all we think about are all the things we think we might be missing",
	"'Cause if we think we are we are",
	"And if we don't we aren't worth the time it takes to think of making love with who we're kissing",
	"They tried to tell us and at times we tried to listen",
	"Someday don't wake up I want you to get some rest",
	"Someday if she's hungry I'll bring her to you",
	"Clara once upon a time your mother didn't love your father the best",
	"But he made believe that she did one day it was true",
	"Go back to sleep my daughter",
	"Go back to sleep my wife",
	"I'm waiting for you there",
	"Someday I wake up and she's still a song to play",
	"Someday but you're ready to hear it's for you",
	"Clara once upon a time your father knew he'd scare your mother away",
	"Singing lovers live in a dream that keeps coming true",
	"Go back to sleep my daughter",
	"Go back to sleep my wife",
	"I'm waiting for you there",
	"It's gonna be a long night",
	"It's gonna be a long night",
	"And the sun may never shine",
	"On what I think I've seen in your eyes",
	"On what I think I've seen in your eyes",
	"'Cause your eyes are not a window",
	"Your eyes are not a window",
	"Your eyes are not a window",
	"They're a one way mirror to my soul",
	"Someday don't wake up I want you to get some rest",
	"I run my fingers through her blackish blondish hair",
	"Look into her brown blue eyes and touch her skin so dark and fair",
	"Because I like how she encourages and scolds me",
	"How even as her left hand pushes me away her right arm holds me",
	"It's nice to know she's always waiting for me at the dead ends",
	"Guess I need a little love from every little square of my sweet little patchwork girlfriend",
	"Of my sweet little patchwork girlfriend",
	"I can't tell if she would rather take or leave me",
	"And I'm not sure what I'm saying but I'm sure I want her to believe me",
	"So I run my fingers through her blackish blondish brownish reddish grayish (grayish?!) hair",
	"And tell her I won't mess around with other girls unless they're her",
	"It's nice to know she's always waiting for me at the dead ends",
	"Guess I need a little love from every little square of my sweet little patchwork girlfriend",
	"Of my sweet little patchwork girlfriend",
	"Though I'm no more boy scout than boyfriend I could see tying the knot",
	"Instead it's my hands that are tied because that'd be against the law even in Utah",
	"It's nice to know she's always waiting for me at the dead ends",
	"Guess I need a little love from every little square of my sweet little patchwork girlfriend",
	"She's anywhere I could ever go ain't no false start or dead end",
	"That could take me away from, couldn't bring me back to my sweet little patchwork girlfriend",
	"Or my big bitter patchwork girlfriend",
	"Or my sweet little patchwork girlfriend",
	"City girls are all the same",
	"They play you like a pinball game",
	"Oh what a summer",
	"Making love to make believe",
	"Their hearts are on not up their sleeves",
	"Oh what a summer to lie",
	"Under violet or to guys that ask for your number",
	"Oh would you wonder why",
	"If I paid a hundred dollars for the chance to see you cry",
	"And a hundred more to see you cry again 'stead a singing",
	"No no body's warmer to the touch than hers but you'll never",
	"Know know anything as cold as the heart of a city girl",
	"This imaginary friend",
	"Can't remember he's pretend",
	"Oh what a summer to lie",
	"Under neon and glass or to me as I ask for your number",
	"Oh would you wonder why",
	"If I paid a hundred dollars for the chance to see you cry",
	"And a hundred more to see ya cry again 'stead a singing",
	"No no body's warmer to the touch than hers but you'll never",
	"Know know anything as cold as the heart of a city girl",
	"We took a hammer and chisel to the cornerstone",
	"'Cause the building had to come down",
	"In a show more pretty than practical",
	"For to satisfy the city girls around",
	"Oh it was beautiful but it fell too soon",
	"Took a few good men and left these city guys",
	"Who would pay a hundred dollars for the chance to see you cry",
	"And a hundred more to see you cry again 'stead a singing",
	"No no body's warmer to the touch than hers but you'll never",
	"Know know anything as cold as the heart of a city girl",
	"If ever I have seen the sunrise and known it's time for bed",
	"If ever I have breathed in deeply",
	"And felt like I was dead",
	"And felt like I was dead",
	"Then I have not been",
	"I have not been in love",
	"If ever I have seen your lips move and known you couldn't say",
	"The words I think could make me love you",
	"And heard them anyway",
	"And heard them anyway",
	"Then I have not been",
	"I have not been in love",
	"I rise as the sun goes down and I pray my true love and I find a way to each other soon or never",
	"Snow falls on the Hudson",
	"Souls are lost by the lonely dozen",
	"She was here and then she wasn't",
	"Out there in the weather",
	"Was it a frostbitten wind or a whisper",
	"I could swear I felt her",
	"If I knew her face",
	"If I knew her name",
	"If I knew would you",
	"How long can my heart live",
	"With the key kept away from its cage of locked ribs",
	"If it's mine why's it in prison",
	"Out there in the weather",
	"Where it's cold as it is bitter",
	"It could die or it could find her",
	"If you knew her face",
	"If you knew her name",
	"If you knew would you",
	"New York City",
	"Would you give her to me",
	"I'd be yours forever",
	"My old man says",
	"If you're good the world gives you",
	"The things you ask for",
	"New York was I wrong when",
	"I built my dreams on a little island",
	"Did I ever really want them",
	"Bridges in all directions",
	"Three in the morning can't believe I never saw them",
	"Maybe I should be going",
	"If she knew my face",
	"If she knew my name",
	"If she knew would you",
	"New York City",
	"Would you give her to me",
	"I'd be yours forever",
	"You know what I'm after",
	"Tell me how many times do I have to ask you",
	"I'd be yours forever",
	"You're right we're wrong for now",
	"Just bailing water while the ship goes down",
	"When we could float away",
	"On separate rafts to die another day",
	"But it's more than time apart my love",
	"It's time to handle this without kid gloves",
	"Ripping the Band-Aid off",
	"May not be pretty least the bleeding's stopped",
	"I think",
	"Let's not fool ourselves",
	"Taking a break is dragging out a breakup too long",
	"Help yourself to whatever you like with whomever you like",
	"But don't get married without me",
	"We lost the battle won",
	"That doesn't mean we can't have any fun",
	"This war's not over yet",
	"We called a truce no need to get upset",
	"I know you know I still love you",
	"Anyone else is a lateral move at best",
	"And who says I'll be able to move at all",
	"'Til I cozy back up to you this fall",
	"But still",
	"Let's not fool ourselves",
	"Taking a break is dragging out a breakup too long",
	"Help yourself to whatever you like with whomever you like",
	"But don't get married without me",
	"Let's not fool ourselves",
	"'Cause we aren't cowards",
	"We aren't liars",
	"We're just two people who are not in love",
	"Right now",
	"Let's not fool ourselves",
	"Taking a break is dragging out a breakup too long",
	"Help yourself to whatever you like with whomever you like",
	"But don't get married without me",
	"The leading lights of the age all wondered amongst themselves what I would do next",
	"After all that I found in my travels around the world, was there anything left?",
	"\"Gentlemen\" I said, \"I've studied the charts and if what I am thinking is right,\"",
	"There's another new world at the top of the world for the first one who breaks through the ice",
	"And I looked around the room, in that way I once had and I saw that they wanted was belief",
	"So I said, \"All I've got are my guts and my God, \" then I paused, \"and the Annabel Lee\"",
	"Oh, the Annabel Lee and I saw their eyes shine, the most beautiful ship in the sea",
	"My Nina, my Pinta, my Santa Maria, and my beautiful Annabel Lee",
	"That spring we set sail, the crowds waved from shore, and on board the crew waved their hats",
	"But I never had family, just the Annabel Lee, so I never had cause to look back",
	"I just set the course north and I'd study the charts and towards dawn I drifted towards sleep",
	"And I dreamed of the fine deep harbor I'd find past the ice, for my Annabel Lee, after that it got colder",
	"The world got quiet, it was never quite day or quite night",
	"And the sea turned the color of sky turned the color of sea turned the color of ice",
	"Till at last all around us was fastness, one vast glassy desert of arsenic white",
	"And the waves that once lifted us, sifted instead into drifts against Annabel's side and the crew gathered closer",
	"At first for the warmth, but each day would bring a new set",
	"Of tracks in the snow leading over the edge of the world till I was the only one left",
	"Then it gets cloudy but it seems like I laid there for days and maybe for months",
	"Oh but Annabel held me, just the two of us happy to think back on all we had done",
	"We talked of the other new worlds we'd discover as she gave up her body to me",
	"And as I chopped up her mainsail for timber I told her of all that we still had to see",
	"As the frost turned her moorings to nine-tail and the winds lashed her sides in the cold",
	"I burned her to keep me alive every night in the loving embrace of her hold",
	"And I won't call it rescue that brought me back here to the old world to drink and decline",
	"And pretend that the search for another new world was well worth the burning of mine",
	"But sometimes at night, in my dreams comes the singing of some unknown tropical bird",
	"And I smile in my sleep, thinking Annabel Lee's finally made it to another new world",
	"Yeah, sometimes at night in my dreams comes a singing of some unknown tropical bird",
	"And I smile in my sleep, thinking Annabel Lee's finally made it to another new world",
	"Way down in Dixie, oh do they miss me",
	"Down along the Dixie Line",
	"Banjos are strumming",
	"Horseflies are humming",
	"Ripe melons on the vine",
	"The gold and the grey weeds",
	"Saying look away",
	"Way down along the Dixie Line",
	"I spent my childhood walking the wildwood",
	"Down along the Dixie Line",
	"Freight trains are squalling",
	"Eyeballs are bawling",
	"Four engines at a time",
	"I was so happy with Momma and Pappy",
	"Down along the Dixie Line",
	"Can't you hear those drivers wail?",
	"Can't you see those bright rails shine?",
	"Wanna catch that fireball man",
	"Leave that North Land far behind",
	"A river of whiskey flows down in Dixie",
	"Down along the Dixie Line",
	"They pulled up the tracks now",
	"I can't go back now",
	"Can't hardly keep from cryin'",
	"Oh do they miss me way down in Dixie",
	"Down along the Dixie Line",
	"Can't you hear those drivers wail?",
	"Can't you see those bright rails shine?",
	"Wanna catch that fireball man",
	"Leave that North Land far behind",
	"Down along the Dixie Line",
	"I've been a moonshiner for seventeen long years",
	"I spend all of my money on whiskey and beer",
	"I'll go down to some hollow and set up my still",
	"I'll sell you a gallon for a ten dollar bill",
	"I go to some bar room and drink with my friends",
	"Where the women can't follow and see what I spend",
	"God bless that pretty women, I wish she was mine",
	"Cuase her breath is as sweet as the dew on the vine",
	"Let me eat when I'm hungry, let me drink when I'm dry",
	"A dollar when I'm hard up, religion when I die",
	"The whole world's a bottle and life's but a dram",
	"When the bottle gets empty it sure ain't worth a damn",
	"I've been a moonshiner for seventeen long years",
	"I spend all of my money on whiskey and beer",
	"I'll go down to some hollow and set up my still",
	"And if whiskey dont kill me then I don't know what will",
	"Get back in your hole, get dead, son",
	"Get back in your hole, get bent",
	"Get back in your hole, get dead, son",
	"Get back in your hole, get bent",
	"Crawl under a rock, get lost, boy",
	"Crawl under a rock, get fucked",
	"Crawl under a rock, get lost, boy",
	"Crawl under a rock, get fucked",
	"Get out of those shoes and grow wings, dear",
	"Get out of those shoes and grow wings",
	"Get out of those shoes and grow wings, dear",
	"Get out of those shoes and grow wings",
	"Get out of those shoes and grow wings, dear",
	"Get out of those shoes and grow wings",
	"Get out of those shoes and grow wings, dear",
	"Get out of those shoes and grow wings",
	"Ha",
	"Ha, ha",
	"Ha",
	"Fall over yourself and break heads, kid",
	"Fall over yourself and break heads",
	"Fall over yourself and break heads, kid",
	"Fall over yourself and break heads",
	"Crawl out of your skin, takes time, pal",
	"Crawl out of your skin, takes time",
	"Crawl out of your skin, takes time, pal",
	"Crawl out of your skin, takes time",
	"Get out of those shoes and grow wings, dear",
	"Get out of those shoes and grow wings",
	"Get out of those shoes and grow wings, dear",
	"Get out of those shoes and grow wings",
	"Get out of those shoes and grow wings, dear",
	"Get out of those shoes and grow wings",
	"Get out of those shoes and grow wings, dear",
	"Get out of those shoes and grow wings",
	"Ha, ha",
	"It's on",
	"Again you hate it but you know it then",
	"You know it and so do your friends",
	"And you can sing together when",
	"It's on",
	"Pretend you love it because you love them",
	"As you explode out of your phones (amen)",
	"to make some music of your own (amen)",
	"You can hate it softly to yourself alone",
	"A man among amens",
	"A ringing bell, or programmed drums or both",
	"I couldn't tell but I rejoice",
	"A smoke machine or a swinging thurible",
	"it was hard to see but I lifted up my voice",
	"We've come together over we know not what..",
	"A call to prayer, or the last for alcohol",
	"we didn't care; We knelt and bowed our heads",
	"Or did we dance? Like we may never get another chance to disconnect",
	"We've come together Over we know not what to say I love you",
	"I love you, I love you",
	"I mean it, I want feel it",
	"God help me feel it",
	"I love you",
	"God knows I mean it",
	"God help me feel it",
	"God knows we mean it",
	"God help us feel it..",
	"We lie in bed",
	"The wireless dancing through my head",
	"Until I fear the space between my breath",
	"I see an end to where I don't love you like I can",
	"Cause I've forgotten how it feels (amen)",
	"To love someone or thing for real (amen)",
	"Darling when you wake, remind me what we've done",
	"That can't be shared, or saved, or even sung",
	"It's on",
	"Again you nod your head and take my hand",
	"Though im not sure where we'll go (amen)",
	"To worship more than what we know (amen)",
	"As long as you're there I won't be alone",
	"A man among amens",
	"I died happy in my sleep",
	"I died happy in my sleep",
	"My children around and you looking down",
	"Heaven's a julep on the porch",
	"Heaven's a julep on the porch",
	"You and me rocking",
	"A grandfather clock is tick, tick, tocking to the time",
	"We used to wind it",
	"She brought the sugar and the mint",
	"She brought the sugar and the mint",
	"And he brought the whiskey",
	"Asked for my blessing",
	"Yes sir I know she's",
	"Heaven's a julep on the porch",
	"Heaven's a julep on the porch",
	"You and me rocking",
	"A grandfather clock is tick, tick, tocking to the time",
	"We used to wind it",
	"Got time",
	"We used to wind it",
	"Now the time stands still",
	"We can drink our fill",
	"Out of silver",
	"That will never",
	"Tarnish like we will",
	"You were just a girl that I should meet",
	"You were the girl that I would meet",
	"For drinks in the backyard",
	"A beautiful daughter",
	"Lifetimes of summer",
	"And love ever after",
	"I died happy in my sleep",
	"I died happy in my sleep",
	"My children around and you looking down",
	"Heaven's a julep on the porch",
	"Heaven's a julep on the porch",
	"You and me rocking",
	"A grandfather clock is tick, tick, tick, tick, tocking to the time",
	"We used to wind it",
	"Got time",
	"We used to wind it",
	"Oh it's tick, tick, tick, tick, tick, tick, tick, tick, tocking to the time",
	"We used to wind it",
	"The sun hits the back of my neck",
	"Through a crack in the window shade",
	"I blow it off",
	"I blow it off",
	"'cause I keep outside",
	"In the eyes and ears",
	"Of friends I've never met",
	"I blow it off",
	"I blow it off",
	"There's nothin' to say",
	"That couldn't just as well be sent",
	"I've got an American share",
	"Of 21st century stress",
	"Your trouble vibrates the table",
	"Interrupts my reverie",
	"I blow it off",
	"I blow it off",
	"'cause if it's that bad",
	"It ain't gettin' better",
	"Face to face with me",
	"So I blow it off",
	"I blow it off",
	"There's nothin' to say",
	"That couldn't just as well be sent",
	"I've got an American share",
	"Of 21st century stress",
	"Go ahead and bloody up your knuckles",
	"Knockin' at my door",
	"I'll blow 'em off",
	"I'll blow em off",
	"'cause there's nothin' to say",
	"That couldn't just as well be sent",
	"We've all got an American share",
	"Of 21st century stress",
	"See the oceans rise and leave the nations",
	"Cryin' at heaven's door",
	"I blew it off",
	"I blew it off",
	"I pinned her to the wall and said",
	"I wanna take you home",
	"I wanna take you home, think about it",
	"She threw me to the floor and said",
	"I wanna take you home",
	"I wanna take you home, think about it",
	"What's the center between two centers of attention?",
	"Is there a center between two centers of attention?",
	"All our attention between two centers of attention and then there's",
	"Cause I'm a magnet",
	"And you're a magnet",
	"And we're pushing each other away",
	"We're pushing each other away",
	"We're pushing each other away",
	"Baby I'm a blank check",
	"And you're a blank check",
	"To whose order we going to pay?",
	"To whose order we going to pay?",
	"To whose order we going to pay?",
	"I laughed away to tears and said what if you took me now",
	"What if you took me here, think about it",
	"She locked the hallway door and said",
	"You gonna take me now",
	"You gonna take me here, don't think about it",
	"But I've thought about it",
	"What's the center between two centers of attention?",
	"Is center of attention is some center of attention?",
	"All our attention between two centers of attention and then there's",
	"Oh yes",
	"Cause I'm a magnet",
	"And you're a magnet",
	"And we're pushing each other away",
	"We're pushing each other away",
	"We're pushing each other away",
	"Oh baby I'm a blank check",
	"And you're a blank check",
	"Our very own order to pay",
	"Our very own order to pay",
	"Our very own order to pay",
	"Cause we're pushing each other away",
	"We're pushing each other away",
	"We're pushing each other away",
	"We're pushing each other away",
	"Cause we're pushing each other away",
	"We're pushing each other away",
	"Baby I'm a magnet",
	"Rise up, blinking in the sun",
	"Wrapped in invisible wire",
	"Something beautiful's gonna come",
	"Out from underneath our thumbs",
	"So let freedom vibrate, not ring",
	"'Cause we can't listen to everyone",
	"Wanna hear ourselves sing",
	"My oh my, what a wonderful day",
	"We're having, we're having",
	"Why, oh why, are we looking for a way",
	"Outside it, outside it",
	"I see the green grass below",
	"I feel the warmth of the spring",
	"Is it beautiful (maybe not, maybe not)",
	"But maybe so",
	"But if it keeps us singing",
	"My oh my, what a wonderful day",
	"We're having, we're having",
	"Why, oh why, are we looking for a way",
	"Outside it, outside it",
	"How long, oh Lord, can you keep the whole world",
	"Spinning under our thumbs?",
	"Boll weevil told the farmer",
	"You better treat me right",
	"I'll eat up all of your cotton",
	"Sleep in your grain rail tonight",
	"Boll weevil told the farmer",
	"You don't need no Ford machine",
	"I'll eat up all of your cotton",
	"Can't buy no gasoline",
	"Yon comes the spider",
	"Crawled up and down the wall",
	"He must've been going",
	"To get his hash's haul",
	"I don't see no water",
	"But I'm about to drown",
	"I don't see no fire",
	"But I'm burning down",
	"Help us on the way",
	"I guess it wasn't mine to say",
	"We're too far gone",
	"But I've been here before",
	"And though it's changed, I know the door",
	"Locks on the outside",
	"A wolf nipped at my heels",
	"I tried to reinvent the wheel",
	"With sticks and straw",
	"And the wrong half of the hourglass",
	"Was full when I heard her voice",
	"On the outside",
	"On the outside",
	"On the outside",
	"Hey there, it's all gonna be fine",
	"You ain't gonna die alone",
	"You ain't gonna be forgotten",
	"[x2]",
	"It's on the outside",
	"It's on the outside",
	"Hey there, it's all gonna be fine",
	"You ain't gonna die alone",
	"You ain't gonna be forgotten",
	"[x4]",
	"I've never dwelled on leaving",
	"Only getting somewhere",
	"But darling I'll miss these evenings",
	"In my fourth floor walk-up",
	"Villagers stumbling below",
	"Trying to catch each other on the very street where I caught you",
	"With three drinks, maybe more",
	"Four blocks in the summer air",
	"And one kiss at my door",
	"We brushed off the cabs",
	"Looked up past the fire escape",
	"To find us looking back",
	"At what we're leaving to get somewhere",
	"Darling I'll keep that apartment",
	"In some loud and reckless recess of my heart",
	"I moved there alone to live with a girl like you",
	"Your love drives it home and I might look over my shoulder",
	"But I'll never dwell on leaving",
	"If I'm getting somewhere",
	"Look at us we're glowing",
	"Tripping the dark fantastic",
	"Singing the phosphorescent pinks and blues",
	"To beloved tunes in beloved rooms",
	"I can love it all to the distractions with this",
	"Look at us hold each other spellbound",
	"Every moment a polished silver",
	"Link in a chain forever rattling through",
	"Our beloved tunes in our beloved rooms",
	"God I've loved you all to the distrations with this",
	"This little light of mine",
	"I'm gonna let it shine",
	"Shine little lights of ours",
	"Like Orion's Belt of stars",
	"Connected only from afar",
	"Shine little lights of ours",
	"Like Orion's Belt of stars",
	"Guide us back to where we are",
	"From where we wanna be",
	"Do you ever feel alone, old pal?",
	"Are you ragged, running low on morale?",
	"Have I got something grand that I've planned for you",
	"Baby, do you burn for glowing power after dark?",
	"In the shadow of some hour you feel the spark?",
	"Have I got something swell that I'll tell to you",
	"You're not alone",
	"For so many years man has suffered the plague of isolation",
	"Isolation from his fellow man, fellow woman, unable to connect",
	"Unable to reach out and touch someone",
	"To be tethered, to be one with the world",
	"But now man and woman can be attuned to every arcane detail",
	"Every dog's bark, every boy's back, every girl's tiara",
	"With a new invention, a staggering development in technology",
	"Sleek White Baby",
	"Keep it by your bedside, maybe",
	"And then how all of your friends",
	"All of our friends",
	"Are here now",
	"Such cheer now",
	"Nine out of ten businessmen agree",
	"The sleek white baby should be your constant companion",
	"Whether you're dining, traveling, moping, convalescing, or eating a sandwich",
	"Don't be the one left out",
	"If you fail to buy our prized new machine",
	"(Why would you do that?)",
	"You will find yourself stung by the sting",
	"(It's painful, really it is)",
	"Of gloom and misery, how you will die alone",
	"(That doesn't sound pleasant, does it?)",
	"Alone, alone, alone, alone",
	"Woooh",
	"Sleek White Baby",
	"They're waking you up to close the bar",
	"The street's wet you can tell by the sound of the cars",
	"The bartender's singing Clementine",
	"As he's turning around the open sign",
	"Dreadful sorry, Clementine",
	"Though you're still her man",
	"It seems a long time gone",
	"Maybe the whole thing's wrong",
	"What if she thinks so",
	"But just didn't say so",
	"You drank yourself into a slow-mo",
	"And made an angel in the snow",
	"Anything to pass the time",
	"And keep that song out of your mind",
	"Oh my darling, oh my darling, oh my darling",
	"Clementine",
	"Dreadful sorry, Clementine",
	"Dreadful sorry, Clementine",
	"Mother, Father: I'm standing",
	"Standing and I'm not about to fall",
	"When I can speak I'll tell you not to worry",
	"Or be sorry for anything",
	"'Cause no one understands this world at all",
	"My father swept me over his shoulders",
	"Above the empty cars to see the fair",
	"A slowly spinning wheel of smiling neighbors",
	"and flowers for my mother",
	"Who sang to me that night of love and death",
	"'Cause everybody sings of love and death",
	"We dreamt our sons and daughters",
	"A high wire, connecting the four corners of the earth",
	"But the wire disappeared and left them standing on nothing",
	"but thin air",
	"They're standing and they're not about to fall",
	"Standing and they're not about to fall",
	"Child you'll grow up",
	"In wonder, like we'll grow old",
	"Like our parents did, and their parents before",
	"It was written on the faces in the waiting room",
	"the day you were born",
	"Child you'll grow up",
	"In wonder, like we'll grow old",
	"Like our parents did, and their parents before",
	"It was written on the faces in the waiting room",
	"The day they, we, and you were born",
	"The day you were born",
	"Mother, listen to my heart. ",
	"Mother, listen to my heart",
	"Just as one beat ends, another starts",
	"You can hear no matter where you are",
	"Sister, hide our love away",
	"From the evil we both know",
	"[Chorus]",
	"It can see you through these dark days",
	"Though they seem to darken as I go",
	"Our love will see us through these dark, dark days sister",
	"'Til it lights the way back home",
	"Sister, hide our love away",
	"It can turn the whole world upside down",
	"Shake it 'til the sky falls to the ground",
	"We don't have to reap the fear they sow",
	"Friends, as long as we hide our love away",
	"In the good they'll never know",
	"[Chorus]",
	"It can see us through these dark days",
	"Though they seem to darken as we go",
	"Our love will see us through these dark, dark days sister",
	"'Til it lights the way back home",
	"Sister, hide our love away",
	"Mother, listen to my heart",
	"Just as one beats ends, another starts",
	"You can hear no matter where you are"
];