module.exports = [
	"Baby's at the punch bowl", 
	"with a glass for you to fill ",
	"if you empty it with her", 
	"in the time she has to kill",
	"Kill kill kill me",
	"Baby's in the punch bowl",
	"wants you to help yourself",
	"and she'll remember nothing",
	"so there'll be nothing to tell",
	"Tell tell tell tell me",
	"I'm not saying, I'm not saying, I'm just saying",
	"Baby's on the punch bowl",
	"gonna ride it off to bed",
	"Yours or any bed'll do really",
	"as long as it ain't the one she left",
	"Left left left left me",
	"Tell me you want me to think ",
	"You can lead me to water you can make me drink",
	"I trust you if you say it's good",
	"You wouldn't hurt me and I don't think you could",
	"Tell me what I don't need to keep",
	"I over-packed and the sidewalk is steep",
	"To your cathedral at the top of Nob Hill",
	"It makes me tired and dear it always will",
	"Tell me why I haven't been healed",
	"I haven't changed and nothings been revealed",
	"And what's in the blood of the way and the light",
	"That takes my sin Sunday morning and",
	"Makes me drunk at night",
	"Tell me that I'm more than a dream,",
	"A golden hell prize you failed to redeem",
	"Don't tell me that you've always known",
	"That I'd wake up first, and you'd wake up alone",
	"The sweet young man",
	"Goes walking down the street",
	"wiping blood off his hands",
	"And it doesn't look good but he does what he can",
	"To erase the signs",
	"Of the nightmare he faced at the scene of the crime",
	"She snuck up behind him",
	"As he knelt by her victim",
	"She whispered I knew you'd come",
	"But there's nothing to be done",
	"And if I were you I'd run",
	"Cause no one cares",
	"About how you felt",
	"When they see any sign of guilt",
	"You kissed its face",
	"You held its hand",
	"You always were a sweet young man",
	"He's still a mess",
	"So he hires a car",
	"To take him to the fountain at Balboa park",
	"Where he used to play",
	"When he was young",
	"I'm back in the moment where I belong",
	"Turns out four years was four years too long",
	"Its over and I'm over it",
	"She sang me a song that I wrote for her",
	"Then she said I like the tune but not the words",
	"Its over and I'm over it",
	"You collected the moments I threw away",
	"Said to yourselves he's gonna want them back",
	"The day it's over",
	"And he's over it",
	"Friends let's drink 'til our hearts break open",
	"And our hands feel empty",
	"Though they're full all the time",
	"It's so nice in here I'm so glad you're here",
	"Can we just stay here all the time",
	"Walk me home we'll watch the sun come up",
	"Don't leave me alone 'cause I've been left enough",
	"It's over I'll get over it",
	"Friends let's drink to my indiscretions",
	"I woke up with a number and a name",
	"That I don't want that I won't use again",
	"But would you proofread any messages I send",
	"O woman I'm your servant",
	"I don't know anything but I'm ready to learn",
	"O woman I'm starving for your approval",
	"Be kind to me",
	"The big city calls and your daughters are smiling",
	"In the windows of apartment buildings",
	"I bet I look about as small as I feel",
	"Thank you jesus can I have another",
	"And another",
	"Thank you lord",
	"But if it pleases thee to have them",
	"Banging down the door",
	"Couldst thou let 'em know what they're in for",
	"Ain't good for you or me or them",
	"Amen",
	"O woman I'm your servant",
	"Asking for the right to look you in the eye",
	"O woman I'm dying for you to notice",
	"How far I've come",
	"I'm moving downtown and your",
	"Daughters are walking by me",
	"I believe they're still deciding",
	"If they like having me around",
	"If they like having me around",
	"I need to know why",
	"Goodwill's coming by to collect a box",
	"I filled with things I hate about myself",
	"Things I liked before I got here",
	"Then it'll pick her up and we'll do",
	"Anything she wants or anything they want",
	"Or anything you want o woman I don't care",
	"Lord I'd be in your debt",
	"If you'd help me forget",
	"That heaven's mine for trying",
	"Cause lord I don't know why",
	"You'd give me so much life",
	"I'm coming back my friends",
	"From the deep and bitter end",
	"Where I was so concerned",
	"That we would be the ones who burned",
	"The more scared the safer",
	"The more grateful for the grape juice",
	"And the wafer",
	"I sound done",
	"And I feel done",
	"But I'm not done",
	"Unless he'd give up on a lost son",
	"I need to hear him say",
	"You and your friends can come in",
	"Your thoughts and that girl can come in",
	"Your parents and brothers are here",
	"I let them in",
	"Who told you I wouldn't let you all in",
	"You are my children",
	"Heaven shine through the stars",
	"The city lights and the nearest bar",
	"Where I'll be with my friends",
	"Hiding from the bitter end",
	"The armor and the weapons",
	"Were a strange way to show them my affection",
	"I sound done",
	"And I feel done",
	"But I'm not done",
	"Nothing nothing then a kiss",
	"In the middle of the street",
	"And I'm loosening my grip",
	"On the throat of a bad dream",
	"Turning gold above your head",
	"A bell to ring me to my knees",
	"Do you darling 'til you're dead",
	"Or do you darling 'til you're bored",
	"With this ringing I thee wed",
	"Nothing then a haloed whore",
	"And an angel that she bribed",
	"And a god he's working for",
	"Come to take me from your side",
	"Where I wake in a cold sweat",
	"Wringing love out of my life",
	"So do you darling 'til you're dead",
	"Or do you darling 'til you're bored",
	"It'll happen",
	"It's gonna happen babe",
	"But it hasn't happened yet",
	"I'm not gonna let you get",
	"ahead of yourself",
	"It's your Achilles heel",
	"Though I want it as bad as you",
	"We've gotta try to see it through",
	"Our own excitement",
	"Your excitement babe",
	"Hasn't let that happen yet",
	"and it won't if you forget",
	"what happened last time",
	"You call me, why do you call me",
	"And why do I answer, when I know",
	"Oh I know you were crying",
	"Why are you crying",
	"And how can you say that, when you know",
	"Oh you know, that you were the sun giving up behind the golden gate",
	"Now you’re the bum begging up and down the lower hate",
	"Oh you know, that you were the band going out to play one more song",
	"Now you’re the giant out on second ‘cause you thought he was gone",
	"I call her, why do I call her",
	"And why does she answer, when she knows",
	"oh she knows I was laughing",
	"Why am I laughing",
	"Oh and how can I say that when I know, oh I know",
	"that I was a fire-escape party over union square",
	"Now I’m a cab driver fucking over every fare",
	"Oh I know, that I was a young Dylan tossing off the perfect verse",
	"Now I’m another damn Yankee can’t toss to first (woohoohoo)",
	"Lord I can’t toss it to first (woohoohoo)",
	"Oh I can’t toss it to first",
	"Oh we know that we were the band going out to play one more song",
	"Now you’re the giant out on second 'cause you thought he was gone…"
];